### ISSUE TITLE
Unreal 5.4 support

### ISSUE THREAD

**Issue by pakona** [DominikPeacock/ue4-new-module-tool#13]
Awesome plugin.

There are various warnings from the Plugin when used in UE 5.4.

E.g:

```
warning C4996: 'FEditorStyle::GetStyleSetName': FEditorStyle::GetStyleSetName() is deprecated, use FAppStyle::GetAppStyleSetName() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
```

Any plans to fix / upgrade the Plugin?

**Comment by pakona** [comment]
Just realized - this is fixed at HEAD (main).

I think it would be nice to get a new release with those fixes : )

**Comment by DominikPeacock** [comment]
Main now contains the changes from the 5.4 branch. Thanks for reaching out.
