### ISSUE TITLE
"Private/Public" include paths don't need to be specified

### ISSUE THREAD

**Issue by Flassari** [DominikPeacock/ue4-new-module-tool#7]
The lines in` {ModuleName}.Build.cs` adding to `PublicIncludePaths` and `PrivateIncludePaths` are redundant. The `Private` and `Public` folders are automatically added as include paths for all modules. I usually advice people to not add anything to `Public/PrivateIncludePaths` as it keeps include paths in code files clear and correct, exceptions when working with frameworks.

**Comment by DominikPeacock** [comment]
Agreed. Fixed starting with 5.0.
